// Procedure Details
export enum SupervisionLevel { //Minimum
  "Primary Surgeon",
  "Secondary Surgeon",
  "Assistant Surgeon",
}

export enum Magnitude {
  "Complex",
  "Intermediate",
  "Major",
  "Minor",
}
export enum Urgency {
  "Elective",
  "Emergency",
  "Planned Day Case",
  "Unplanned Readmission",
  "Urgent",
}

export enum Complications { //Multiple
  "Abandoned TURP",
  "Abdominal Pain",
  "Abdominal/pelvis collection",
  "Acute Brain Syndrome",
  "Acute Renal Impairment",
  "Aesthetic major",
  "Aesthetic minor",
  "Anaemia",
  "Anaesthetic complication",
  "Anastomotic leak",
  "Anastomotic Leak (bowel)",
  "Anastomotic Leak (ureteroileal)",
  "Anastomotic revision",
  "Arrhythmia",
  "Atrial Fibrillation",
  "Avulsed ureter",
  "Bile duct - retained stone",
  "Bile duct injury",
  "Bile leak requiring intervention",
  "Bile leak settling spontaneously",
  "Bladder Wall Perforation extraperitoneal vs transperitoneal",
  "Bleeding - Haematoma",
  "Bleeding - Postoperative Haemorrhage",
  "Bleeding - Requiring intervention or hospitalisation",
  "Bleeding requiring haemostatic therapy",
  "Blocked / Dislodged SPC (requiring operation)",
  "Blood Transfusion",
  "Bowel Obstruction Requiring Surgery",
  "Cardio-respiratory instability",
  "Cardiovascular - Cardiac Arrest",
  "Cardiovascular - CVA / TIA",
  "Cardiovascular - Myocardial Infarction",
  "Cardiovascular - Myocardial Ischaemia",
  "Cardiovascular - Stroke",
  "Chest Infection",
  "Clinical anastomotic leak",
  "Compartment syndrome",
  "Confusion Episode",
  "Conversion to Laparotomy",
  "CSF leak",
  "CVA",
  "Damage to other viscus",
  "Dehydration - IV rehydration",
  "Diabetes Mellitus (exacerbation)",
  "Diarrhoea - antibiotic related",
  "Diarrhoea - infective",
  "Dislocation",
  "Dural Tear",
  "Electrolyte imbalance",
  "Enterocolitis",
  "Enterocutaneous fistula",
  "Epilepsy",
  "Exacerbation arthritis / gout",
  "Exacerbation of Dementia",
  "Failed Embolisation",
  "Failed PUJ repair Open",
  "Failed stone removal",
  "Failed Trial of Void",
  "False Urethral Passage",
  "Fat necrosis",
  "Fistula",
  "Fixation failure",
  "Flap failure complete",
  "Flap failure partial",
  "Fractured stent",
  "Gastric Band Leak",
  "General - Adverse Drug Reaction",
  "General - Confusion",
  "General - Death",
  "General - Fall",
  "General - Fall with fracture",
  "General - Fever requiring hospitalisation for IV antibiotics",
  "General - Unplanned return to theatre",
  "Genitourinary - UTI requiring further antibiotics but not IV",
  "Graft failure complete",
  "Graft failure partial",
  "Haematuria - postoperative clot retention",
  "Haemorrhage - return to theatre",
  "Haemorrhage - transfusion required",
  "Hepatobiliary (Bile leak, cholecystitis etc)",
  "Hernia",
  "Hydronephrosis - nephrostomy / stent",
  "Hypospadias fistula",
  "Ileus / Bowel Obstruction (conservative)",
  "Implant failure / extrusion",
  "Inadvertent Durotomy",
  "Incomplete Excision",
  "Infection - Abscess (not wound infection)",
  "Infection - Cannula site",
  "Infection - Clinically significant local",
  "Infection - MRSA",
  "Infection - VRE",
  "Intra-abdominal abscess",
  "Intraoperative fracture",
  "Intussusception perforation",
  "Intussusception recurrence",
  "Laparoscopic Conversion to Open - Adhesions",
  "Laparoscopic Conversion to Open - Failure to progress",
  "Laparoscopic Conversion to Open - Organ Injury",
  "Laparoscopic Conversion to Open - Vascular Injury",
  "Laparoscopic Introperative complication (other)",
  "Lymphatic system (chyle leak etc)",
  "Lymphocoele",
  "Major organ dysfunction - Acute renal failure",
  "Major organ dysfunction - ARDS",
  "Major organ dysfunction - Cholestatic jaundice",
  "Major organ dysfunction - Hepatic failure",
  "Major organ dysfunction - Multiorgan",
  "Major organ dysfunction - Shock or hypotension requiring inotropic support",
  "Malunion",
  "Metabolic / Electrolyte imbalance",
  "Nausea / Vomiting",
  "Neobladder prolonged leak",
  "Nephrostomy - blocked",
  "Nephrostomy - dislodged",
  "Nerve injury",
  "Neurological defecit",
  "Neuropraxia / pressure area",
  "Nipple Necrosis",
  "Non union",
  "None",
  "Obturator Nerve Injury",
  "Other",
  "Pain Syndrome",
  "Pancreatic Abscess",
  "Pancreatitis",
  "PCNL Adjacent organ injury (eg colon)",
  "PCNL Damage to Kidney requiring prolonged drainage",
  "PCNL Embolisation",
  "PCNL Haemorrhage requiring transfusion",
  "PCNL Prolonged haematuria",
  "Perforation",
  "Peripheral vascular disease",
  "Pleural effusion",
  "Pneumothorax (chest drain)",
  "Postoperative atelactasis",
  "Postoperative Corr Calcium less than 2.0mmol/L",
  "Postoperative fever >48hrs",
  "Postoperative Haematoma",
  "Postoperative Haematoma - Conservative",
  "Postoperative Haematoma - Conservative Drainage (open or percutaneous)",
  "Post-operative haemorrhage",
  "Postoperative ileus",
  "Post-operative intra-abdominal infection",
  "Postoperative pain requiring referral to pain clinic",
  "Postoperative Pain requiring stent insertion",
  "Postoperative Urinoma - Conservative",
  "Postoperative Urinoma Drainage (open/percutaneous)",
  "Post-operative wound infection",
  "Pressure sores",
  "Procedure abandoned",
  "Prolonged length of stay",
  "Pseudo obstruction",
  "Pseudocyst",
  "Pulmonary Embolus",
  "Pyloromyotomy perforation",
  "Radiological anastomotic leak",
  "Rectal Injury - oversewn",
  "Rectal Injury - stoma and reoperation",
  "Renal Failure Requiring Dialysis",
  "Reoperation unplanned",
  "Respiratory - Pneumonia",
  "Respiratory Failure",
  "Retained Stent",
  "Retention of urine",
  "Sepsis - Bacteraemia/septicaemia",
  "Sepsis - Endocarditis",
  "Sepsis - Line related",
  "Sepsis - Septic shock",
  "Septacemia",
  "Seroma",
  "Sinus",
  "Small bowel obstruction",
  "Splenectomy",
  "Stent / Nephrostomy - dislodged",
  "Stent syndrome/stent removal",
  "Subphrenic abscess",
  "Superficial wound dehiscence",
  "Temporary recurrent laryngeal nerve palsy",
  "Tendon rupture",
  "Thromboembolism",
  "Thrombosis - DVT",
  "Thrombosis - PE",
  "Total wound dehiscence",
  "TURP syndrome",
  "Unplanned ICU admission",
  "Unplanned readmission after discharge",
  "Ureteric Injury",
  "Ureteric perforation",
  "Ureteric transection",
  "Urethral Stricture",
  "Urethral Stricture late comp",
  "Urethrolysis for retention post incontinence procedure",
  "Urinary Retention",
  "Urinary tract infection",
  "Urinoma / Collection / Abscess - drainage",
  "Urosepsis",
  "Use of reversal agents (naloxone and flumazenil)",
  "Wound breakdown or dehiscence",
  "Wound erythema",
  "Wound excessive bleeding",
  "Wound infection (discharge of pus)",
  "Wound infection requiring further surgery",
}

export enum ComplicationGrade {
  "CD1: Deviation from normal postoperative course without need for surgical, radiological, endoscopic or pharmacological interventions, EXCEPTING anti-emetics, anti-pyretics, analgesics, diuretics, electrolytes, physiotherapy & wounds opened at bedside",
  "CD2: Requiring pharmacological treatment (other than that allowed for CD1), including blood transfusion or TPN",
  "CD3a: Complication which necessitates intervention, surgical, endoscopic or radiological, NOT REQUIRING GENERAL ANAESTHESIA",
  "CD3b: Complication which necessitates intervention, surgical, endoscopic or radiological, REQUIRING GENERAL ANAESTHESIA",
  "CD4a: Life threatening complications requiring ICU management: SINGLE ORGAN DYSFUNCTION, INCLUDING DIALYSIS",
  "CD4b: Life threatening complications requiring ICU management: MULTIORGAN DYSFUNCTION",
  "CD5: Death",
}
